name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *
    
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare
        run: mkdir output
      - name: Build Vauxite
        run: podman run --privileged -v "$(pwd)/output":/output -it quay.io/charles2/vauxiteiso
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.iso
