name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 1 * *'
    
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Get current date
        id: date
        run: |
          echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - name: Prepare
        run: mkdir output
      - name: Build PupaOS c9s
        run: sudo podman run --privileged -v "$(pwd)/output":/output codeberg.org/pupaos/iso:c9s
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: Build on ${{ steps.date.outputs.date }}
          files: |
            output/*.iso
