name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
    
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Prepare
        run: mkdir output
      - name: Build PupaOS a9
        run: sudo podman run --privileged -v "$(pwd)/output":/output git.almalinux.org/pupaos/iso:a9
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: Build on ${{ steps.date.outputs.date }}
          files: |
            output/*.iso
